### create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "david.ceraniccc@gmail.com",
    "password": "asdf"
}

### find user
GET http://localhost:3000/auth/2


### find all
GET http://localhost:3000/auth?email=david.ceraniccc@gmail.com

### delete
DELETE http://localhost:3000/auth/1

### patch
PATCH http://localhost:3000/auth/33
content-type: application/json

{
    "email": "david.ceranic@gmail.com"
}